[project]
name = "liteocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.79.0",
    "pynput>=1.8.1",
    "pyperclip>=1.9.0",
    "pyside6>=6.9.0",
]
