name: Build with Nuitka

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -e .[build]
          pyside6-rcc resources/resources.qrc -o src/liteocr/resources_rc.py

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/liteocr/main.py
          mode: app
          enable-plugins: pyside6
          nofollow-import-to: |
            numpy
          windows-console-mode: disable
          windows-icon-from-ico: resources/icons/icon.png
          macos-app-icon: resources/icons/icon.png
          macos-app-name: LiteOCR
          linux-icon: resources/icons/icon.png

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**
          include-hidden-files: true
